### ISSUE TITLE
Compile failed with nginx 1.13.10 / 1.15.0

### ISSUE THREAD

**Issue by Apollo2000** [vozlt/nginx-module-stream-sts#7]
`/configure --with-http_slice_module --with-http_ssl_module --with-http_realip_module --with-http_mp4_module --with-http_geoip_module --with-http_flv_module --with-threads --with-http_stub_status_module --add-module=/root/nginx-rtmp-module-1.2.1/ --add-module=/root/nginx-module-vts  --add-module=/root/nginx-module-stream-sts --add-module=/root/nginx-module-sts`

Problem when i run make i get errors: 
`In file included from /root/nginx-module-sts/src/ngx_http_stream_server_traffic_status_module.c:9:0:
/root/nginx-module-sts/src/ngx_http_stream_server_traffic_status_module.h:15:24: fatal error: ngx_stream.h: No such file or directory
 #include <ngx_stream.h>
                        ^
compilation terminated.
objs/Makefile:1751: recipe for target 'objs/addon/src/ngx_http_stream_server_traffic_status_module.o' failed
make[1]: *** [objs/addon/src/ngx_http_stream_server_traffic_status_module.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from /root/nginx-module-sts/src/ngx_http_stream_server_traffic_status_shm.c:9:0:
/root/nginx-module-sts/src/ngx_http_stream_server_traffic_status_module.h:15:24: fatal error: ngx_stream.h: No such file or directory
 #include <ngx_stream.h>
                        ^
compilation terminated.
objs/Makefile:1765: recipe for target 'objs/addon/src/ngx_http_stream_server_traffic_status_shm.o' failed
make[1]: *** [objs/addon/src/ngx_http_stream_server_traffic_status_shm.o] Error 1
In file included from /root/nginx-module-sts/src/ngx_http_stream_server_traffic_status_node.c:9:0:
/root/nginx-module-sts/src/ngx_http_stream_server_traffic_status_module.h:15:24: fatal error: ngx_stream.h: No such file or directory
 #include <ngx_stream.h>`

Seem like  can't find Nginx file (https://github.com/nginx/nginx-releases/blob/master/src/stream/ngx_stream.h)

debian 9, checking for OS
 + Linux 4.9.0-6-amd64 x86_64
checking for C compiler ... found
 + using GNU C compiler
 + gcc version: 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)

We have no problem to build vts. Problem is only on sts modules.

Thank you for your great job!

**Comment by vozlt** [comment]
Please try adding the `--with-stream`.
Thanks.

**Comment by Apollo2000** [comment]
SOLVED

Thank you!
